// <auto-generated />
namespace MVCRiceStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddClientOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddClientOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "201506290654177_AddClientOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
